spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${OPTI_DB_URL}
    username: ${OPTI_DB_USERNAME}
    password: ${OPTI_DB_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${OPTI_MAIL_USERNAME}
    password: ${OPTI_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  graphhopperApi:
    baseUrl: https://graphhopper.com/api/1/route
    reverseGeoCoding: https://graphhopper.com/api/1/geocode
    key: ${GRAPHHOPER_API_KEY}

  jwt:
    expirationTimeInMs: 43200000
    secret: ${JWT_SECRET}

  mail:
    expirationTimeInMin: 15
    confirmationLink:  http://localhost:8080/api/v1/auth/confirm?token=

